spring.application.name=fbcoach

spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASS:}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=postgresql

spring.main.allow-circular-references: true

spring.mvc.cors.allowed-origins=http://localhost:5173

#logging.level.org.hibernate=DEBUG
#logging.level.org.springframework.orm.jpa=DEBUG

#if you want to change the default port(8080), uncomment the line below and set your desired port
#server.port=7070
